version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  slack: circleci/slack@4.1

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Creating artifacts
          working_directory: ~/search-yc-top-companies
          command: |
              mkdir /tmp/react-app
              cp -r "~/search-yc-top-companies" /tmp/react-app
        
      - store_artifacts:
          path: /tmp/react-app
          destination: react-app
  status:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Sending status"
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: master
      - status:
          requires:
            - build
            - heroku/deploy-via-git
